name: Release Beta
on:
  workflow_dispatch:
      inputs:
        userEmail:
          description: 'User Email'     
          required: true
          default: 'sampath@lightful.com'
        PackageKey:
          description: 'Package Installation Key'     
          required: true
          default: 'test1234'
    
jobs:
  setup-org:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'release/*.*.*'
        fetch-depth: 20

    # Installs Salesforce CLi
    - name: Install Salesforce CLI
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/stable/sfdx-cli-linux-x64.tar.xz
        mkdir sfdx
        tar xJf sfdx-cli-linux-x64.tar.xz -C sfdx --strip-components 1
        ./sfdx/install
        sfdx --version
        
    - name: Install jq
      run: |
        sudo apt-get install jq
    - name: Authenticate to Dev Hub org
      run: |
        echo "${{secrets.SFL_SECRET_KEY}}" | base64 -d > server.key 
        sfdx auth:jwt:grant -u ${{secrets.SFL_USERNAME}} -f server.key -i ${{secrets.SFL_CONSUMER_KEY}} -r https://login.salesforce.com
        sfdx config:set defaultdevhubusername=${{secrets.SFL_USERNAME}}
    
    - name: Create new version
      run: |
        sfdx force:package:version:create -x -p "GIFter" -k ${{ github.event.inputs.PackageKey }} -w 60 --codecoverage
        new_version_id=$(grep -o "04t[[:alnum:]]\{15\}" sfdx-project.json | tail -n1)
        echo "version_id=${new_version_id}" >> $GITHUB_ENV
